config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'welcome/index'
  get 'welcome/somos'
  get 'welcome/cardapio'
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :users
  resources :password_resets

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, :on => :create
    validates :password, length: { minimum: 6 }, :allow_blank => true
    validates :email, uniqueness: true
=begin
    before_create { generate_token(:auth_token)} 
=end

    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    include SessionsHelper

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email enviado para alterar senha."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Pedido de nova senha expirou."
    elsif @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
      redirect_to root_url, :notice => "Senha alterada!"
    else
      render :edit
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index]
  before_action :same_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(["name LIKE ?","%#{params[:search]}%"])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Conta criada com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Cadastro alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Cadastro excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :adress)
    end

    def impede_nao_logado
      if !logged_in?
          redirect_to root_path
      end
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end 


    def authorize
      unless admin?
          redirect_to root_path
          false
      end
    end

    def same_user
      redirect_to root_path if current_user.id!=@user.id and not admin?
      false
    end


    def admin?
        current_user.moderator?
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def somos
  end

  def cardapio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end


    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pedepizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <header>
      <nav>
        <div>
          <%= image_tag("/assets/logoPedePizza.png", class:"imgheader") %>
        </div>
        <%= link_to 'Pé de Pizza', root_path, class:"pedepizza" %>
        <ul>
          <% if !logged_in?%>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Cadastre-se', new_user_path %></li>
          <% else %>
            <li><%= link_to "Sair", logout_path, method: :delete %></li>
            <li><%= link_to current_user.name, current_user %></li>
          <% end %>
          <li><%= link_to 'Quem somos', welcome_somos_path %></li>
          <li><%= link_to 'Cardápio', welcome_cardapio_path %></li>
          <li><a href="#">Delivery</a></li>
        </ul>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="contatos">
        <h2>Contatos:</h2>
        <ul>
          <li>Tel:(21)1234-4321</li>
          <li>Wpp:(21)91234-4321</li>
        </ul>
      </div>
      <div class="socialicons">
          <a href="https://pt-br.facebook.com/" target="_blank"><%= image_tag("/assets/facebook.png", class:"imgcontatos") %></a>
          <a href="https://www.instagram.com/?hl=pt-br" target="_blank"><%= image_tag("/assets/instagram.png", class:"imgcontatos") %></a>
        </div>
    </footer>

  </body>
</html>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    
    <div class="newpass">
        <div class="field">
            <%= f.label :password, "Nova senha", class:"logfield" %>
            <%= f.password_field :password %>
        </div>

        <div class="actions">
            <%= f.submit "Gerar nova senha", class:"regbox" %>
        </div>
    </div>

<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>

    <div class="newpass">
        <h2 class="novasenha">Nova Senha</h1>
        <div class="field">
            <%= label_tag :email,"E-mail", :class => "logfield" %>
            <%= text_field_tag :email, params[:email]%>
        </div>

        <div class="action">
            <%= submit_tag "Nova Senha", class:"regbox" %>
        </div>
    </div>

<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cadastro">
    <div class="field">
      <%= form.label :Nome, class:"regfield" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label "E-mail", class:"regfield" %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :Senha, class:"regfield" %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :Endereço, class:"regfield" %>
      <%= form.text_area :adress %>
    </div>

    <div class="actions">
      <%= form.submit "Cadastrar", class:"regbox" %>
    </div>

    <%= link_to 'Voltar', root_path, class:"regbox" %>

  </div>

<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <div class="editando_user">

    <div class="field">
      <%= form.label :Nome, class:"regfield" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label "E-mail", class:"regfield" %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :Senha, class:"regfield" %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :Endereço, class:"regfield" %>
      <%= form.text_area :adress %>
    </div>

    <div class="actions">
      <%= form.submit "Salvar", class:"regbox" %>
    </div>

  </div>

<% end %>

app/views/users/index.html.erb
<h2 class="usuarios">Usuários</h2>

<div class="index_users">
  <p id="notice"><%= notice %></p>

<div class="pesquisa">
  <%= form_tag users_path, :method => 'get' do%>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Pesquisar", class:"searchbox" %>
  <% end %>
</div>

  <table class="table_users">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Endereço</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.adress %></td>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
          <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="showuser">
  <p id="notice"><%= notice %></p>

  <p>
    <strong class="logfield">Nome:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong class="logfield">E-mail:</strong>
    <%= @user.email %>
  </p>

  <% if !@user.moderator %>
    <p>
      <strong class="logfield">Endereço:</strong>
      <%= @user.adress %>
    </p>
  <% end %>

  <% if !@user.moderator%>
    <%= link_to 'Editar', edit_user_path(@user), class:"linkforgot"%>
  <% end %>
  <% if @user.moderator%>
    <div class="menu_mod">
      <%= link_to "Index de Usuários", users_path, class:"linkforgot"%>
      <a href="#", class="linkforgot">Index de Promoções</a>
      <a href="#", class="linkforgot">Index de Produtos</a>
    </div>
  <% end %>

</div>

app/views/welcome/cardapio.html.erb
<h2 class="Sabores">Sabores</h2>

<div class="quadrosab">
    <%= image_tag("/assets/pizza1.jpeg", class:"imgmenu") %>
    <%= image_tag("/assets/pizza2.jpeg", class:"imgmenu") %>
    <%= image_tag("/assets/pizza3.jpeg", class:"imgmenu") %>
    <%= image_tag("/assets/pizza4.jpeg", class:"imgmenu") %>
    <p class="menucapt">Pizza de calabresa</p>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
    </head>

    <body>

        <h2 id="promos">Promoções!</h2>
        <div class="quadropromos">
            <%= image_tag("/assets/pizza1.jpeg", class:"imgmenu") %>
            <%= image_tag("/assets/pizza2.jpeg", class:"imgmenu") %>
            <%= image_tag("/assets/pizza3.jpeg", class:"imgmenu") %>
            <p class="promocapt">Pizza de calabresa</p>
            <p class="promocapt">Pizza de calabresa</p>
            <p class="promocapt">Pizza de calabresa</p>
        </div>
    </body>

</html>

app/views/welcome/somos.html.erb
<h2 class="Somos">Quem somos</h2>

<%= image_tag("/assets/PizzaioloPedepizza.jpg", class:"imgsomos") %>

<p class="psomos">Lorem Ipsum Muito textão daquele jeito, pra encher uma página mesmo. Escreve escreeve escreve escreve. Pra ficar igual uma descrição da história de uma pizzaria. Muita coisa mesmo. Olha quanta palavra. Escreve pra ser feliz, se não escrever, não vai ser feliz. Anota isso aí. Fica aqui minha indignação, tem que acabar a felicidade, falo com tranquilidade. </p>